language: java

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
  - tar xvzf jdk-17_linux-x64_bin.tar.gz
  - rm -r jdk-17_linux-x64_bin.tar.gz
  - mv ./jdk-17.0.2 $HOME/jdk-17.0.2
  - export JAVA_HOME=$HOME/jdk-17.0.2
  - export PATH=$PATH:$JAVA_HOME/bin
  - chmod +x gradlew

script:
  - ./gradlew clean build

before_deploy:
  - zip -r forkie ./build/libs/* ./appspec.yml ./scripts/*
  - mkdir -p deploy
  - mv forkie.zip deploy/forkie.zip

deploy:
  - provider: s3
    on:
      repo: Forkie-Player/Forkie-Player-Back
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: forkie-deploy-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    on:
      repo: Forkie-Player/Forkie-Player-Back
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: forkie-deploy-bucket
    key: forkie.zip
    bundle_type: zip
    application: forkie-player-server
    deployment_group: forkie-player-server-group
    region: ap-northeast-2
    travis_wait: 50
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - oh980225@gmail.com